name: tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0", "8.3"]
        tarantool: ["2.11", "3.0", "3.1"]
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
      - run: docker run -d -p 3301:3301 tarantool/tarantool:${{ matrix.tarantool }}
      - run: vendor/bin/phpunit tests
